### ISSUE TITLE
Can't output two different files from same tree

### ISSUE THREAD

**Issue by fredrikekelund** [aaronshaf/broccoli-requirejs#10]
I'm trying to compile two different JS files from my `scripts` tree. A logical way to go about this seemed to be to run this filter on my tree twice, with two different configurations. However, doing so produces some really strange errors that, to me, resembles a race condition or something.

Here's the relevant part of my `Brocfile`

```js
var rjsOptions = {
    baseUrl: "scripts",
    inlineText: true,
    optimize: "uglify",
    stubModules: ["text"],
    paths: {
        knockout: "empty:"
    }
};

var fooScript = requireJs(scripts, {
    requirejs: _.extend(rjsOptions, {
        include: ["foo"],
        insertRequire: ["main"],
        mainConfigFile: "scripts/main.js",
        name: "main",
        out: "scripts/main.js"
    })
});

var barScript = requireJs(scripts, {
    requirejs: _.extend(rjsOptions, {
        insertRequire: ["bar"],
        mainConfigFile: "scripts/main.js",
        name: "bar",
        out: "scripts/bar.js"
    })
});

module.exports = mergeTrees([
    fooScript,
    barScript
]);
```

And here's the error output I'm getting (the error is being thrown when merging the trees):

```bash
$ broccoli build build
Error: Merge error: file scripts/bar.js exists in /home/fredrik/app/tmp/require_js_filter-tmp_dest_dir-yMHQNi3F.tmp and /home/fredrik/app/tmp/require_js_filter-tmp_dest_dir-C8Wv970J.tmp
Pass option { overwrite: true } to mergeTrees in order to have the latter file win.
  at mergeRelativePath (/home/fredrik/app/node_modules/broccoli-merge-trees/index.js:98:21)
  at mergeRelativePath (/home/fredrik/app/node_modules/broccoli-merge-trees/index.js:122:17)
  at /home/fredrik/app/node_modules/broccoli-merge-trees/index.js:23:5
  at $$$internal$$tryCatch (/home/fredrik/app/node_modules/broccoli-merge-trees/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:490:16)
  at $$$internal$$invokeCallback (/home/fredrik/app/node_modules/broccoli-merge-trees/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:502:17)
  at $$$internal$$publish (/home/fredrik/app/node_modules/broccoli-merge-trees/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:473:11)
  at Object.$$rsvp$asap$$flush [as _onImmediate] (/home/fredrik/app/node_modules/broccoli-merge-trees/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1581:9)
  at processImmediate [as _immediateCallback] (timers.js:345:15)


Build failed
```

If I do pass {overwrite: true} to the mergeTrees call, **I get the output of the first requireJs call (ie. the scripts/main.js), but with the filename bar.js.**

I asked a [question on StackOverflow](http://stackoverflow.com/questions/28268380/error-building-two-different-files-from-same-tree-with-broccoli-requirejs) about this as well, but this seems to be more of a bug than a misunderstanding on my part, so I thought I'd report it.

**Comment by dfournier** [comment]
Hi!

Did you try to export only `fooScript`? I think the filter run the optimizer tool but also keep the sources. Can you please confirm this?

**Comment by fredrikekelund** [comment]
I tested again, and it seems that even if I `module.exports` only the first or the second tree, I get only one file - scripts/bar.js with the content of scripts/main.js.

**Comment by dfournier** [comment]
That's weird, it looks like calling the filter twice has a side effect. We are currently working on a new version with updated packages. I think I'll publish a version this weekend. Will you be available to try it again?

**Comment by fredrikekelund** [comment]
I know, super weird... I'm doing some debugging and it looks like the requirejs.optimize call in both callbacks is receiving the exact same result (content of the first call, `options.out` file name from the 2nd call), so it's definitely a problem with requirejs. For some reason requirejs.optimize, if called twice, overrides *parts* of the first config with the 2nd config.

And yeah, I can absolutely do more testing. If it's the #9 PR, I can go ahead and try it beforehand to let you know if that helps as well?

**Comment by dfournier** [comment]
It would help a lot :+1:

**Comment by fredrikekelund** [comment]
Getting the same result even with the patch :/

**Comment by dfournier** [comment]
I'll keep in my your problem and tell you asap when it's fixed

**Comment by fredrikekelund** [comment]
I found the problem! So silly...

It's my call to `_.extend` that overwrites the config object. If I simply change the order of the arguments I pass to `_.extend`, it works as expected.

```js
var fooScript = requireJs(scripts, {
    requirejs: _.extend({
        include: ["foo"],
        insertRequire: ["main"],
        mainConfigFile: "scripts/main.js",
        name: "main",
        out: "scripts/main.js"
    }, rjsOptions)
});
```

**Comment by dfournier** [comment]
Sorry, I should have noticed it earlier! `_.extend` mutates the first parameter. When you want another reference do like this `_.extend({}, rjsOptions, {...})`

**Comment by fredrikekelund** [comment]
Yeah, I should've caught that one... Anyway, thanks for taking the time to respond :)
