### ISSUE TITLE
Pass in options directly instead of through options.requirejs

### ISSUE THREAD

**Issue by fredrikekelund** [aaronshaf/broccoli-requirejs#11]
Passing in the options directly seems to make more sense. Basically if it looked like this:

```js
var tree = requireJs("lib", {
    name: 'index',
    out: 'bundle.js'
});
```

Instead of like this:
```js
var tree = requireJs("lib", {
	requirejs: {
		name: 'index',
		out: 'bundle.js'
	}
});
```

Is there a reason it doesn't look like this currently? If such a change was made, internally the current syntax could still be supported `if (options.requirejs)` or something.

**Comment by dfournier** [comment]
You're right, I thought the same thing. For the next version I don't know yet if it'll be like this. But the filter will not support both syntaxes. Since the readme is also deprecated, maybe next version will be a breaking one.

**Comment by fredrikekelund** [comment]
Cool, looking forward to the new release!
