### ISSUE TITLE
non-serializable attributes unhandled

### ISSUE THREAD

**Issue by bblack** [aaronshaf/broccoli-requirejs#15]
Options that do not serialize well cause problems. I assume this is because options are being json-serialized in this line in https://github.com/aaronshaf/broccoli-requirejs/blob/master/index.js#L47 :

```
child.send(options);
```

For example, `fileExclusionRegExp` is typically a RegExp, and passing such an object to `JSON.stringify` returns `{}`, and eventually causes

```
TypeError: Object #<Object> has no method 'test'
```

**Comment by dfournier** [comment]
Hi!

Thanks for the issue, you're right about it. I don't have time right now to fix it up, I think I'll be able to work on it this weekend.

Fell free to open a PR if you have a patch!

**Comment by dfournier** [comment]
Hi!

I found a way to fix it. Right now I'm writing some tests. If you need a quick fix I can create you a special branch, just tell me :smile:

**Comment by dfournier** [comment]
Hey @bblack!

Now it should work with `1.0.3` version. Could you please confirm it?

**Comment by bblack** [comment]
Super late with this, but yes, it does work. Thanks!
